apiVersion: v1
kind: Service
metadata:
  name: test-app-svc
  namespace: test-metrics
spec:
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
