apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-deployment
  namespace: lbc-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
      - name: backstage
        image: fash01/backstage:v1
        ports:
        - containerPort: 7007


